name: Freshwriting CI
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
      env:
        ImageOS: ubuntu18

    - name: Install bundler
      run: gem install bundler -v 1.17.3

    - name: Install bundled dependencies
      run: bundle install --without development debug doc

    - name: start mysql DB
      run: sudo service mysql start

    - name: copy example files
      run: |
        cp config/database.example.yml config/database.yml
        
    # - name: create fresh_writing_test DB
    #   run:  mysql -e "CREATE DATABASE fresh_writing_test;" -uroot -proot

    - name: Prepare database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:test:prepare

    - name: Run rake spec
      env:
        RAILS_ENV: test
      run: bundle exec rake spec